version: '3.3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: hospital_app
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    networks:
      - hospital_network
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    depends_on:
      - db

  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: hospital_db
    env_file:
      - .env
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_PID=Express
    ports:
      - "1433:1433"
    volumes:
      - mssql_data:/var/opt/mssql
    restart: unless-stopped
    networks:
      - hospital_network

networks:
  hospital_network:
    driver: bridge

volumes:
  mssql_data:
